### Health Check
GET http://localhost:3000/api/v1/health
Accept: application/json

### Test /places Endpoint (Valid Request)
GET http://localhost:3000/api/v1/places?lat=-22.90968200167603&lon=-43.56191949837622&radius=300&page=1&limit=10&cache=false
Accept: application/json

### Test all places Endpoint (Valid Request)
GET http://localhost:3000/api/v1/all-places
Accept: application/json

### Test /places Endpoint (Missing Parameters)
GET http://localhost:3000/api/v1/places
Accept: application/json

###

### Test /places Endpoint (Invalid Parameters)
GET http://localhost:3000/api/v1/places?lat=1000&lon=2000&radius=-1&page=-5&limit=0
Accept: application/json

###

### Test /places Endpoint (Excessive Radius and Limit)
GET http://localhost:3000/api/v1/places?lat=40.7128&lon=-74.0060&radius=10000&page=1&limit=200
Accept: application/json

### TAJ MAHAL
GET http://localhost:3000/api/v1/places?lat=-22.909682&lon=-43.564864&radius=100&page=1&limit=5&cache=false

### FUJI
GET http://localhost:3000/api/v1/places?lat=35.3606&lon=138.7274&radius=400&page=1&limit=10&cache=false